defaults:
  - algorithm: mappo
  - environment: pettingzoo_mw
  - scenario: raw

  - algorithm_parameters: ${algorithm}
  - environment_parameters: ${environment}
  - optional environment_scenario: ${environment}/${scenario}
  - eval_scenario: ${environment}/${scenario}
  - override hydra/launcher: submitit_local
  - _self_

wandb:
  wandb_name: 02s
  wandb_group: latest
  wandb_project: mw_skill

model:
  save_group: latest
  model_path: default

eval_settings:
  general:
    seed: 42
    eval_episodes: 2 
    eval_threads: 1

  functions:
    # 是否只读取文件，进行数值计算
    load_results: False
    result_file_name: hi

    # 是否渲染
    render: False
    render_episodes: 5

    # 是否进行ablation
    ablation: False
    
    # 是否使用gpu
    use_gpu: False

    # 是否导出角度数据
    export_angle_data: False



hydra:
  searchpath:
    - file://sources/skill/1.config/global
  launcher:
    timeout_min: 6000
    gpus_per_node: 1
  run:
    dir: ./results/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./results/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}